#!/bin/bash

# See https://github.com/aelsabbahy/goss/releases for release versions
# curl -L https://github.com/aelsabbahy/goss/releases/download/_VERSION_/goss-linux-amd64 -o /usr/local/bin/goss
# chmod +rx /usr/local/bin/goss

# (optional) dgoss docker wrapper (use 'master' for latest version)
# curl -L https://raw.githubusercontent.com/aelsabbahy/goss/_VERSION_/extras/dgoss/dgoss -o /usr/local/bin/dgoss
# chmod +rx /usr/local/bin/dgoss

#OS=$(awk '/DISTRIB_ID=/' /etc/*-release | sed 's/DISTRIB_ID=//' | tr '[:upper:]' '[:lower:]')
#ARCH=$(uname -m | sed 's/x86_//;s/i[3-6]86/32/')
#VERSION=$(awk '/DISTRIB_RELEASE=/' /etc/*-release | sed 's/DISTRIB_RELEASE=//' | sed 's/[.]0/./')
#
#if [ -z "$OS" ]; then
#  OS=$(awk '{print $1}' /etc/*-release | tr '[:upper:]' '[:lower:]')
#fi
#
#if [ -z "$VERSION" ]; then
#  VERSION=$(awk '{print $3}' /etc/*-release)
#fi
#
#echo $OS
#echo $ARCH
#echo $VERSION

GOSS_LOCATION=https://github.com/aelsabbahy/goss/releases/download/v0.3.3/goss-linux-amd64
DGOSS_LOCATION=https://raw.githubusercontent.com/aelsabbahy/goss/master/extras/dgoss/dgoss
INSTALL_DIR=./bin
EXIT_CODE=0

# Set your GOSS_PATH to the above location
export GOSS_PATH=~/bin

function clean {
  if [ ! -d "$INSTALL_DIR" ] ; then
    mkdir $INSTALL_DIR
  fi
  rm $INSTALL_DIR/*goss 2>/dev/null
}

function install {
  curl -L $GOSS_LOCATION -o $INSTALL_DIR/goss
  chmod +x $INSTALL_DIR/goss

  curl -L $DGOSS_LOCATION -o $INSTALL_DIR/dgoss
  chmod +x $INSTALL_DIR/dgoss
}

function testje {
  echo "Start van dgoss run." 
  dgoss run -p 8081:80 nginx:1.11.10
  EXIT_CODE=$?
}

clean
install 
testje 
clean
exit $EXIT_CODE
